[[ ! -d ~/dev ]] && mkdir ~/dev && chmod o+w dev
[[ ! -d ~/dev/ansible ]]              && git clone https://github.com/mysidlabs/ansible-labs ~/dev/ansible
[[ ! -d ~/dev/k8s-demo ]]             && git clone https://github.com/mysidlabs/k8s-demo.git ~/dev/k8s-demo
[[ ! -d ~/dev/cpuhog ]]               && git clone https://github.com/mysidlabs/cpuhog ~/dev/cpuhog

alias kubectl=oc

PS1="\u \w # "
